### ISSUE TITLE
Retrying on EINTR in networking tests

### ISSUE THREAD

**Issue by justyoyo123** [Lind-Project/safeposix-rust#175]
When debugging networking_tests.rs using RR, some tests received an EINTR from the debugging tool. Since this signal is coming externally, we should retry the failed syscall if it receives an EINTR. The syscall that is failing is the recv_syscall. The tests below are the ones that received this signal:

ut_lind_net_select()
ut_lind_net_socketpair()
ut_lind_net_udp_simple()
ut_lind_net_udp_connect()
ut_lind_net_dns_rootserver_ping()

They are also commented on the testing_domsock branch of safeposix.

**Comment by yizhuoliang** [comment]
yeah, I was also assigned for the `getsockopt` issue, I just looked at what the net syscalls do and skim thru the net tests file. But, there is no main function in that file, the wiki doesn't talk about unit test neither, would you briefly tell me what is the procedure to call the unit test functions? Thank you!

**Comment by justyoyo123** [comment]
So to run these tests, you go into the safeposix-rust directory and run `cargo test --lib` which will run the unit tests. After it runs. at the top you will see a path starting with target/ and whatever else that follows. You copy that path, and then do `rr record (paste target path here)`. Then do `rr replay`, and set a breakpoint at one of these tests. For example, to set a breakpoint at ut_lind_net_select, do `b ut_lind_net_select' and then continue (press `c` ) and it will take you to that test. Then step through until you hit the recv_syscall it is getting the signal on. Sometime before hitting this call, you should also set a breakpoint at recv_syscall so when you hit that in the unit test, you will be able to step through recv_syscall and see exactly when it is getting that signal.

**Comment by yizhuoliang** [comment]
> So to run these tests, you go into the safeposix-rust directory and run `cargo test --lib` which will run the unit tests. After it runs. at the top you of the output, you will see a path starting with target/ and whatever else that follows. You copy that path, and then do `rr record (paste target path here)`. Then do `rr replay`, and set a breakpoint at one of these tests. For example, to set a breakpoint at ut_lind_net_select, do `b ut_lind_net_select` and then continue (press `c` ) and it will take you to that test. Then step through (press `n`) until you hit the recv_syscall it is getting the signal on. Sometime before hitting this call, you should also set a breakpoint at recv_syscall so when you hit that in the unit test, you will be able to step through recv_syscall and see exactly when it is getting that signal.

Thank you! I see how to run the tests, but in this develop branch, the test failed and terminated at the second test, which is an FS test I think, I'm wondering how to skip this one or jump to the network tests?
<img width="1199" alt="image" src="https://github.com/Lind-Project/safeposix-rust/assets/70337586/5b004de4-5693-44a8-95f0-205944830f73">

**Comment by justyoyo123** [comment]
I think you should move to the branch `merge_domsocks_3`, and then make a new branch off of that and make your changes there. Just so that when you push new changes, it wont be directly to develop and you'll have the changes I made to make some of the non-EINTR errors go away. I fixed the errors on the merge_domsocks_3 branch so it shouldn't error in other tests, but to be safe you can just comment lines 38 and 44 inside mod.rs in the `safeposix-rust/src/tests/` directory so it will just run net_tests.

**Comment by yizhuoliang** [comment]
Hi justin, when I uncomment the socketpair() unit test, there is an error occurs about failing the socket assertion
<img width="983" alt="image" src="https://github.com/Lind-Project/safeposix-rust/assets/70337586/c300831b-02aa-4783-b09f-a50d53a6c773">
<img width="557" alt="image" src="https://github.com/Lind-Project/safeposix-rust/assets/70337586/3987e6a8-38db-4fb8-9e81-21111ecda12f">
But note that, line 978 assertion is successful, so the message is sent but not received. I don't think this is an error you mentioned for this issue, but is this a problem you were aware of? Should I take a look on this or bypass and move on to the EINTR issue?

**Comment by justyoyo123** [comment]
Yeah so when you try to debug this error in RR, you'll see it gets an EINTR signal but this is coming from outside. To get past this, you need to check in recv_syscall if it receives an EINTR and if so, retry recv_syscall. This should help you get past and debug the actual problem in this test that is causing that error.

**Comment by yizhuoliang** [comment]
The `recv` looks fine now, under `merge_domsocks_3_coulson`. So the EINTR thing is fixed.

However, he `ut_lind_net_dns_rootserver_ping` test still fails, I asserted that the `recvfrom_syscall` doesn't return an error, and I also checked the ip address of engineering.nyu.edu is correct, and the content parsing looks fine as well. Would you like to take a look on this, this is at line 1330 of `networking_tests.rs` on my branch

**Comment by yizhuoliang** [comment]
The above problem was because the wrong hex ecoding of the engineering website ip, now it's fixed and all tests are passing in the branch 'merge_domsocks_3_coulson'
